### ISSUE TITLE
Feature request: nodename in the jobs list

### ISSUE THREAD

**Issue by e-kotov** [Dando18/slurm-dashboard#119]
I sometimes run singularity containers on interactive nodes in HPC. The most important piece of information I need about the job is the name of the node that started my container, so I can connect to it in a new instance of VScode via SSH.

Currently, to get the node name, I have to manually run `squeue -u {myusername}` in the console.

Would it be possible to optionally display the node name (from the nodelist column of the squeue output) alongside the job name? Perhaps this would be especially useful for jobs that run on a single node.

**Comment by Dando18** [comment]
Hi, I pushed a PR (#121) and [release](https://marketplace.visualstudio.com/items?itemName=danielnichols.slurm-dashboard) to add this.

If you set `slurm-dashboard.job-dashboard.showJobInfo` to `true` you should be able to see the nodelist in the dropdown. Unfortunately there's not much space in the job bar itself to display it next to the job name.
Let me know if this helped!

**Comment by e-kotov** [comment]
@Dando18 perfect, that works! thank you so much!
