### ISSUE TITLE
Feature request: add quick button to go to error log as well as output log

### ISSUE THREAD

**Issue by reesekneeland** [Dando18/slurm-dashboard#150]
Right now in the dashboard, there is a quick command to open the output log file for a slurm job, but there is no button to quickly open the error log, which is more often the one I need to reference. Another small quick button to access this would be useful!

**Comment by Dando18** [comment]
Hi, thanks for leaving an issue!

I did see this and think it's a good idea. Sadly, dissertation work has gotten the best of me the past weeks, but I'll try to make a PR sometime soon.

**Comment by Dando18** [comment]
Hi! The [newest release](https://github.com/Dando18/slurm-dashboard/releases/tag/v0.0.14) has this added.
Let me know if you have any issues!
