### ISSUE TITLE
Invalid numbers in time string UNLIMITED

### ISSUE THREAD

**Issue by lihaojie87** [Dando18/slurm-dashboard#31]
When I open this in vscode, there is a message:
Invalid numbers in time string UNLIMITED
and the jobs area is empty
![image](https://github.com/Dando18/slurm-dashboard/assets/50283726/c942bae2-b2c1-4c86-967b-15dbae063ffb)

**Comment by Dando18** [comment]
Thanks for reporting @lihaojie87

I did not realize jobs could have a time value of `UNLIMITED` :)
Just to confirm, if you run `squeue --job <jobId> -O JobID,Name,TimeLimit,TimeUsed` for that job ID is it only the `TimeLimit` column that shows UNLIMITED or is it both?

**Comment by lihaojie87** [comment]
$ squeue --job 7645 -O JobID,Name,TimeLimit,TimeUsed
JOBID               NAME                TIME_LIMIT          TIME
7645                vasp                365-00:00:00        53:20
here is the output

**Comment by Dando18** [comment]
@lihaojie87 I attempted a fix in #32 and put up a v0.0.9 release with the changes. Let me know if that fixed it.

**Comment by lihaojie87** [comment]
Yes,the bug is fixed.
Thank you!
but it do not support array job verywell
you can see my dashboard
![image](https://github.com/Dando18/slurm-dashboard/assets/50283726/c9d98f06-9174-44a5-ba83-76a03bc468a8)
Maybe it need an another feature.
Anyway,thank you!

**Comment by Dando18** [comment]
Glad that's working!

I'm hoping to add better job array support sometime in the future :)
