### ISSUE TITLE
Is the vscode min-version needed

### ISSUE THREAD

**Issue by AgFlore** [Dando18/slurm-dashboard#55]
The project now has a vscode min-version mandate of `1.85.1`.
https://github.com/Dando18/slurm-dashboard/blob/df81059dc92825603753bca1731967b710511d8c/package.json#L18

For some reason, i have to work on vscode 1.81.1 (versions after which incompatible with Windows 7), and finding myself blocked by this mandate. 
Is this mandate required by some new vscode API used by the extension? If it's just an arbitrary choice, i would be very grateful if you can change it lower.

**Comment by Dando18** [comment]
Hi, thanks for pointing this out!

I had it set this way since I wasn't testing with older vscode versions. 
I added CI testing for more vscode releases in #56 and it looks like 1.81.1 passes all the tests. I'll bump a release soon with the updated constraint.

**Comment by Dando18** [comment]
This has been uploaded in a release: [v0.0.11](https://marketplace.visualstudio.com/items?itemName=danielnichols.slurm-dashboard)

Let me know if there are any issues.
