### ISSUE TITLE
Search for job scripts in specific folders ?

### ISSUE THREAD

**Issue by N-Hoffmann** [Dando18/slurm-dashboard#98]
Hello Daniel! Thank you very much for this nice extension. I use slurm daily and it saves me from using squeue, sbatch and tracking log files a lot :) .

I wanted to know if it was possible to add an option to specify which folders to include and exclude in the job script detection process. I use a workspace that contains folders of all our lab members, but I only need it do detect scripts that are in my own folders in that workspace.
It also looks for scripts that are in my home folder under ```.vscode-server/data/User/History/``` that I don't need, so it would be great if I could exclude them.

Thank you very much once again!

**Comment by Dando18** [comment]
Hi @N-Hoffmann, thanks for opening the issue!

I had previously considered replacing the `slurm-dashboard.submit-dashboard.jobScriptExtensions` setting with a setting for a list of glob patterns to look for. `"**/*.slurm", "**/*.job", "**/*.sbatch"` would be the defaults.

I may go ahead and do this anyways since it's more general than just extensions.
Do you think this would suit your case?

**Comment by N-Hoffmann** [comment]
Hi again, thanks for following on this issue!

Yes, I think that having a list of configurable paths like you suggest should cover my usecase.
Thank you!

**Comment by e-kotov** [comment]
> Do you think this would suit your case?

That would be great!

**Comment by Dando18** [comment]
Hi, I pushed a fix to this in #122 and the [new release](https://marketplace.visualstudio.com/items?itemName=danielnichols.slurm-dashboard).

Now you can use `slurm-dashboard.submit-dashboard.jobScriptPatterns` to pass glob patterns for specifying the job scripts. There may still be an issue with grabbing the CWD, but it seemed to work okay on at least one system I tested on.
Let me know if this helped!

**Comment by e-kotov** [comment]
Thank you, works well!

In case others also have some trouble setting up, the correct way seems to be:

```
"slurm-dashboard.submit-dashboard.jobScriptPatterns": [
        "**/jobs/*.slurm"
    ],
```

With my jobs located in `~/jobs/`

Not something like:

```
"slurm-dashboard.submit-dashboard.jobScriptPatterns": [
        "~/jobs/*.slurm"
    ],
```

or:

```
"slurm-dashboard.submit-dashboard.jobScriptPatterns": [
        "/usr/users/myusername/jobs/*.slurm"
    ],
```

**Comment by N-Hoffmann** [comment]
Hi, sorry for the late reply.
Yes, it works perfectly, thank you very much!
